/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MiwhyMiwh (https://sketchfab.com/MiwhyMiwh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-cafe-072557761595488cb5cc314332455925
Title: Cute Café
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Glass_cabinet2_0: THREE.Mesh;
    Glass_Outline_0: THREE.Mesh;
    kitchen_counter_counter_0: THREE.Mesh;
    kitchen_counter_Outline_0: THREE.Mesh;
    tap_counter_0: THREE.Mesh;
    tap_Outline_0: THREE.Mesh;
    cuttingboard_counter_0: THREE.Mesh;
    cuttingboard_Outline_0: THREE.Mesh;
    Blender_Blender_0: THREE.Mesh;
    Blender_Outline_0: THREE.Mesh;
    liquid_Blender_0: THREE.Mesh;
    liquid_Outline_0: THREE.Mesh;
    Coffe_machine_coffe_machine_industrial_0: THREE.Mesh;
    Coffe_machine_Outline_0: THREE.Mesh;
    tap001_coffe_machine_industrial_0: THREE.Mesh;
    tap001_Outline_0: THREE.Mesh;
    lever_big_coffe_machine_industrial_0: THREE.Mesh;
    lever_big_Outline_0: THREE.Mesh;
    lever_small_coffe_machine_industrial_0: THREE.Mesh;
    lever_small_Outline_0: THREE.Mesh;
    Blender_glass_Blender2_0: THREE.Mesh;
    Blender_glass_Outline_0: THREE.Mesh;
    Mix_Mix_0: THREE.Mesh;
    Mix_Outline_0: THREE.Mesh;
    Mix_glass_Mix_glas_0: THREE.Mesh;
    Mix_glass_Outline_0: THREE.Mesh;
    Cup_thingi_Walls_addons_0: THREE.Mesh;
    Cup_thingi_Outline_0: THREE.Mesh;
    Cup_Cups_0: THREE.Mesh;
    Cup_Outline_0: THREE.Mesh;
    Cup_medium_Cups_0: THREE.Mesh;
    Cup_medium_Outline_0: THREE.Mesh;
    Cup_tall_Cups_0: THREE.Mesh;
    Cup_tall_Outline_0: THREE.Mesh;
    Cup_small_Cups_0: THREE.Mesh;
    Cup_small_Outline_0: THREE.Mesh;
    Coffe_machine001_coffe_machine_industrial_0: THREE.Mesh;
    Coffe_machine001_Outline_0: THREE.Mesh;
    lever_big001_coffe_machine_industrial_0: THREE.Mesh;
    lever_big001_Outline_0: THREE.Mesh;
    lever_small001_coffe_machine_industrial_0: THREE.Mesh;
    lever_small001_Outline_0: THREE.Mesh;
    counter_counter_0: THREE.Mesh;
    counter_Outline_0: THREE.Mesh;
    shelf_shelf_0: THREE.Mesh;
    shelf_Outline_0: THREE.Mesh;
    Micro_micro_0: THREE.Mesh;
    Micro_Outline_0: THREE.Mesh;
    beans_coffe_holder_0: THREE.Mesh;
    beans_Outline_0: THREE.Mesh;
    Glas_pink_cup_pink_0: THREE.Mesh;
    Glas_pink_Outline_0: THREE.Mesh;
    Glas_yellow_cup_white_0: THREE.Mesh;
    Glas_yellow_Outline_0: THREE.Mesh;
    container001_coffe_holder_0: THREE.Mesh;
    container001_Outline_0: THREE.Mesh;
    container002_coffe_holder_glass_0: THREE.Mesh;
    container002_Outline_0: THREE.Mesh;
    beans001_coffe_holder_0: THREE.Mesh;
    beans001_Outline_0: THREE.Mesh;
    container003_coffe_holder_0: THREE.Mesh;
    container003_Outline_0: THREE.Mesh;
    container004_coffe_holder_glass_0: THREE.Mesh;
    container004_Outline_0: THREE.Mesh;
    cactus_cactus_0: THREE.Mesh;
    cactus_Outline_0: THREE.Mesh;
    cactus001_cactus_0: THREE.Mesh;
    cactus001_Outline_0: THREE.Mesh;
    cactus002_cactus_0: THREE.Mesh;
    cactus002_Outline_0: THREE.Mesh;
    bean_bag_coffe_bag_0: THREE.Mesh;
    bean_bag_Outline_0: THREE.Mesh;
    tap002_coffe_machine_industrial_0: THREE.Mesh;
    tap002_Outline_0: THREE.Mesh;
    teapot_teapot_0: THREE.Mesh;
    teapot_Outline_0: THREE.Mesh;
    teapot_bottom_teapot_0: THREE.Mesh;
    teapot_bottom_Outline_0: THREE.Mesh;
    Viewer_cabinet_0: THREE.Mesh;
    Viewer_Outline_0: THREE.Mesh;
    bean_bag001_coffe_bag_0: THREE.Mesh;
    bean_bag001_Outline_0: THREE.Mesh;
    Cup_small001_Cups_0: THREE.Mesh;
    Cup_small001_Outline_0: THREE.Mesh;
    Cup_medium001_Cups_0: THREE.Mesh;
    Cup_medium001_Outline_0: THREE.Mesh;
    smoke_smoke_0: THREE.Mesh;
    smoke001_smoke_0: THREE.Mesh;
    Chair_Chair_red_0: THREE.Mesh;
    Chair_Outline_0: THREE.Mesh;
    saucer_plate_0: THREE.Mesh;
    saucer_Outline_0: THREE.Mesh;
    saucer001_plate_0: THREE.Mesh;
    saucer001_Outline_0: THREE.Mesh;
    coffee_liquid_Cups_0: THREE.Mesh;
    coffee_liquid2_Cups_0: THREE.Mesh;
    Chair001_Chair_yellow_0: THREE.Mesh;
    Chair001_Outline_0: THREE.Mesh;
    Chair002_Chair_pink_0: THREE.Mesh;
    Chair002_Outline_0: THREE.Mesh;
    saucer002_plate_0: THREE.Mesh;
    saucer002_Outline_0: THREE.Mesh;
    Cake_orange_Cake_orange_0: THREE.Mesh;
    Cake_orange_Outline_0: THREE.Mesh;
    Cake_orange001_Cake_orange_0: THREE.Mesh;
    Cake_orange001_Outline_0: THREE.Mesh;
    Cake_orange002_Cake_orange_0: THREE.Mesh;
    Cake_orange002_Outline_0: THREE.Mesh;
    Cake_strawberry_Cake_strawberry_0: THREE.Mesh;
    Cake_strawberry_Outline_0: THREE.Mesh;
    Cupcake_Cupcake_0: THREE.Mesh;
    Cupcake_Outline_0: THREE.Mesh;
    Display_Walls_addons_0: THREE.Mesh;
    Display_Outline_0: THREE.Mesh;
    Display001_Walls_addons_0: THREE.Mesh;
    Display001_Outline_0: THREE.Mesh;
    Floor_Walls_floor_0: THREE.Mesh;
    Floor_Outline_0: THREE.Mesh;
    Painting_Walls_addons_0: THREE.Mesh;
    Painting_Outline_0: THREE.Mesh;
    Souffle_Souffle_0: THREE.Mesh;
    Souffle_Outline_0: THREE.Mesh;
    Walls_Walls_floor_0: THREE.Mesh;
    Walls_Outline_0: THREE.Mesh;
  };
  materials: {
    cabinet2: THREE.MeshBasicMaterial;
    Outline: THREE.MeshBasicMaterial;
    counter: THREE.MeshBasicMaterial;
    Blender: THREE.MeshBasicMaterial;
    coffe_machine_industrial: THREE.MeshBasicMaterial;
    Blender2: THREE.MeshBasicMaterial;
    material: THREE.MeshBasicMaterial;
    Mix_glas: THREE.MeshBasicMaterial;
    Walls_addons: THREE.MeshBasicMaterial;
    Cups: THREE.MeshBasicMaterial;
    shelf: THREE.MeshBasicMaterial;
    micro: THREE.MeshBasicMaterial;
    coffe_holder: THREE.MeshBasicMaterial;
    cup_pink: THREE.MeshBasicMaterial;
    cup_white: THREE.MeshBasicMaterial;
    coffe_holder_glass: THREE.MeshBasicMaterial;
    cactus: THREE.MeshBasicMaterial;
    coffe_bag: THREE.MeshBasicMaterial;
    teapot: THREE.MeshBasicMaterial;
    cabinet: THREE.MeshBasicMaterial;
    smoke: THREE.MeshBasicMaterial;
    Chair_red: THREE.MeshBasicMaterial;
    plate: THREE.MeshBasicMaterial;
    Chair_yellow: THREE.MeshBasicMaterial;
    Chair_pink: THREE.MeshBasicMaterial;
    Cake_orange: THREE.MeshBasicMaterial;
    Cake_strawberry: THREE.MeshBasicMaterial;
    Cupcake: THREE.MeshBasicMaterial;
    Walls_floor: THREE.MeshBasicMaterial;
    Souffle: THREE.MeshBasicMaterial;
  };
};

type ActionName = "Scene";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function AnimeCafe(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    "/anime_cute_cafe.glb",
  ) as GLTFResult;
  const { actions } = useAnimations<GLTFActions>(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="4abdeb655123415b96fe53a66c5d5b48fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Glass"
                  position={[170.812, 454.557, 92.205]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[134.118, 116.637, 156.235]}
                >
                  <mesh
                    name="Glass_cabinet2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Glass_cabinet2_0.geometry}
                    material={materials.cabinet2}
                  />
                  <mesh
                    name="Glass_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Glass_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="kitchen_counter"
                  position={[-1135.082, 238.818, 650.966]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="kitchen_counter_counter_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.kitchen_counter_counter_0.geometry}
                    material={materials.counter}
                  />
                  <mesh
                    name="kitchen_counter_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.kitchen_counter_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="tap"
                  position={[-873.586, 494.875, 1284.951]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={107.467}
                >
                  <mesh
                    name="tap_counter_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.tap_counter_0.geometry}
                    material={materials.counter}
                  />
                  <mesh
                    name="tap_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.tap_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="cuttingboard"
                  position={[-368.265, 390.914, 1063.897]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="cuttingboard_counter_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.cuttingboard_counter_0.geometry}
                    material={materials.counter}
                  />
                  <mesh
                    name="cuttingboard_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.cuttingboard_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Blender"
                  position={[-1803.896, 516.249, 1081.409]}
                  rotation={[-Math.PI / 2, 0, 0.808]}
                  scale={99.643}
                >
                  <mesh
                    name="Blender_Blender_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Blender_Blender_0.geometry}
                    material={materials.Blender}
                  />
                  <mesh
                    name="Blender_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Blender_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="liquid"
                  position={[-1790.215, 812.693, 1069.373]}
                  rotation={[-Math.PI / 2, 0, 0.808]}
                  scale={99.643}
                >
                  <mesh
                    name="liquid_Blender_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.liquid_Blender_0.geometry}
                    material={materials.Blender}
                  />
                  <mesh
                    name="liquid_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.liquid_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Coffe_machine"
                  position={[-1862.046, 729.907, 507.531]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[131.159, 141.428, 174.835]}
                >
                  <mesh
                    name="Coffe_machine_coffe_machine_industrial_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Coffe_machine_coffe_machine_industrial_0.geometry
                    }
                    material={materials.coffe_machine_industrial}
                  />
                  <mesh
                    name="Coffe_machine_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Coffe_machine_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="tap001"
                  position={[-1792.973, 670.47, 517.011]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[131.159, 141.428, 174.835]}
                >
                  <mesh
                    name="tap001_coffe_machine_industrial_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.tap001_coffe_machine_industrial_0.geometry}
                    material={materials.coffe_machine_industrial}
                  />
                  <mesh
                    name="tap001_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.tap001_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="lever_big"
                  position={[-1731.24, 737.197, 553.245]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[131.159, 141.428, 174.835]}
                >
                  <mesh
                    name="lever_big_coffe_machine_industrial_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.lever_big_coffe_machine_industrial_0.geometry
                    }
                    material={materials.coffe_machine_industrial}
                  />
                  <mesh
                    name="lever_big_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.lever_big_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="lever_small"
                  position={[-1814.699, 842.911, 334.378]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[131.159, 141.428, 174.835]}
                >
                  <mesh
                    name="lever_small_coffe_machine_industrial_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.lever_small_coffe_machine_industrial_0.geometry
                    }
                    material={materials.coffe_machine_industrial}
                  />
                  <mesh
                    name="lever_small_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.lever_small_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Blender_glass"
                  position={[-1804.739, 516.249, 1080.604]}
                  rotation={[-Math.PI / 2, 0, 0.808]}
                  scale={99.643}
                >
                  <mesh
                    name="Blender_glass_Blender2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Blender_glass_Blender2_0.geometry}
                    material={materials.Blender2}
                  />
                  <mesh
                    name="Blender_glass_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Blender_glass_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Mix"
                  position={[-1976.942, 629.192, -604.971]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={142.835}
                >
                  <mesh
                    name="Mix_Mix_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mix_Mix_0.geometry}
                    material={materials.material}
                  />
                  <mesh
                    name="Mix_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mix_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Mix_glass"
                  position={[-1976.907, 642.121, -602.4]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={142.835}
                >
                  <mesh
                    name="Mix_glass_Mix_glas_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mix_glass_Mix_glas_0.geometry}
                    material={materials.Mix_glas}
                  />
                  <mesh
                    name="Mix_glass_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Mix_glass_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Cup_thingi"
                  position={[-871.836, 1111.173, 1335.789]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[88.423, 187.061, 187.061]}
                >
                  <mesh
                    name="Cup_thingi_Walls_addons_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cup_thingi_Walls_addons_0.geometry}
                    material={materials.Walls_addons}
                  />
                  <mesh
                    name="Cup_thingi_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cup_thingi_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Cup"
                  position={[-489.442, 1050.163, 1281.741]}
                  rotation={[-1.588, 0.678, 0.286]}
                  scale={100}
                >
                  <mesh
                    name="Cup_Cups_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cup_Cups_0.geometry}
                    material={materials.Cups}
                  />
                  <mesh
                    name="Cup_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cup_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Cup_medium"
                  position={[-998.551, 941.382, 1295.344]}
                  rotation={[-1.588, 0.68, 0.287]}
                  scale={100}
                >
                  <mesh
                    name="Cup_medium_Cups_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cup_medium_Cups_0.geometry}
                    material={materials.Cups}
                  />
                  <mesh
                    name="Cup_medium_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cup_medium_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Cup_tall"
                  position={[-1376.64, 1037.681, 1281.741]}
                  rotation={[-1.619, 0.79, 0.352]}
                  scale={100}
                >
                  <mesh
                    name="Cup_tall_Cups_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cup_tall_Cups_0.geometry}
                    material={materials.Cups}
                  />
                  <mesh
                    name="Cup_tall_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cup_tall_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Cup_small"
                  position={[-698.37, 979.672, 1299.87]}
                  rotation={[-1.594, 0.706, 0.302]}
                  scale={100}
                >
                  <mesh
                    name="Cup_small_Cups_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cup_small_Cups_0.geometry}
                    material={materials.Cups}
                  />
                  <mesh
                    name="Cup_small_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cup_small_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Coffe_machine001"
                  position={[-1862.046, 729.907, -92.532]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[131.159, 141.428, 174.835]}
                >
                  <mesh
                    name="Coffe_machine001_coffe_machine_industrial_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.Coffe_machine001_coffe_machine_industrial_0.geometry
                    }
                    material={materials.coffe_machine_industrial}
                  />
                  <mesh
                    name="Coffe_machine001_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Coffe_machine001_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="lever_big001"
                  position={[-1731.24, 737.197, -46.818]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[131.159, 141.428, 174.835]}
                >
                  <mesh
                    name="lever_big001_coffe_machine_industrial_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.lever_big001_coffe_machine_industrial_0.geometry
                    }
                    material={materials.coffe_machine_industrial}
                  />
                  <mesh
                    name="lever_big001_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.lever_big001_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="lever_small001"
                  position={[-1814.699, 842.911, -265.685]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[131.159, 141.428, 174.835]}
                >
                  <mesh
                    name="lever_small001_coffe_machine_industrial_0"
                    castShadow
                    receiveShadow
                    geometry={
                      nodes.lever_small001_coffe_machine_industrial_0.geometry
                    }
                    material={materials.coffe_machine_industrial}
                  />
                  <mesh
                    name="lever_small001_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.lever_small001_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="counter"
                  position={[-473.227, 239.628, -746.81]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="counter_counter_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.counter_counter_0.geometry}
                    material={materials.counter}
                  />
                  <mesh
                    name="counter_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.counter_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="shelf"
                  position={[-1318.773, 1447.842, 628.136]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="shelf_shelf_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.shelf_shelf_0.geometry}
                    material={materials.shelf}
                  />
                  <mesh
                    name="shelf_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.shelf_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Micro"
                  position={[-1803.375, 1714.999, 446.967]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={92.304}
                >
                  <mesh
                    name="Micro_micro_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Micro_micro_0.geometry}
                    material={materials.micro}
                  />
                  <mesh
                    name="Micro_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Micro_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="beans"
                  position={[-1082.593, 1678.853, 1129.39]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={61.592}
                >
                  <mesh
                    name="beans_coffe_holder_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.beans_coffe_holder_0.geometry}
                    material={materials.coffe_holder}
                  />
                  <mesh
                    name="beans_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.beans_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Glas_pink"
                  position={[-1999.031, 1652.452, -574.469]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={105.688}
                >
                  <mesh
                    name="Glas_pink_cup_pink_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Glas_pink_cup_pink_0.geometry}
                    material={materials.cup_pink}
                  />
                  <mesh
                    name="Glas_pink_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Glas_pink_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Glas_yellow"
                  position={[-1999.031, 1655.474, -278.111]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={105.688}
                >
                  <mesh
                    name="Glas_yellow_cup_white_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Glas_yellow_cup_white_0.geometry}
                    material={materials.cup_white}
                  />
                  <mesh
                    name="Glas_yellow_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Glas_yellow_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="container001"
                  position={[-1079.651, 1852.209, 1129.911]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={69.633}
                >
                  <mesh
                    name="container001_coffe_holder_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.container001_coffe_holder_0.geometry}
                    material={materials.coffe_holder}
                  />
                  <mesh
                    name="container001_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.container001_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="container002"
                  position={[-1080.673, 1731.999, 1131.028]}
                  rotation={[-Math.PI / 2, 0, 2.381]}
                  scale={69.633}
                >
                  <mesh
                    name="container002_coffe_holder_glass_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.container002_coffe_holder_glass_0.geometry}
                    material={materials.coffe_holder_glass}
                  />
                  <mesh
                    name="container002_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.container002_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="beans001"
                  position={[-1474.042, 1688.632, 1128.958]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[108.917, 109.269, 64.229]}
                >
                  <mesh
                    name="beans001_coffe_holder_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.beans001_coffe_holder_0.geometry}
                    material={materials.coffe_holder}
                  />
                  <mesh
                    name="beans001_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.beans001_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="container003"
                  position={[-1469.337, 2024.673, 1129.792]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={111.367}
                >
                  <mesh
                    name="container003_coffe_holder_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.container003_coffe_holder_0.geometry}
                    material={materials.coffe_holder}
                  />
                  <mesh
                    name="container003_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.container003_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="container004"
                  position={[-1470.971, 1837.658, 1131.578]}
                  rotation={[-Math.PI / 2, 0, 2.381]}
                  scale={111.367}
                >
                  <mesh
                    name="container004_coffe_holder_glass_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.container004_coffe_holder_glass_0.geometry}
                    material={materials.coffe_holder_glass}
                  />
                  <mesh
                    name="container004_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.container004_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="cactus"
                  position={[-1911.096, 2026.679, 1080.781]}
                  rotation={[-Math.PI / 2, 0, -1.188]}
                  scale={106.496}
                >
                  <mesh
                    name="cactus_cactus_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.cactus_cactus_0.geometry}
                    material={materials.cactus}
                  />
                  <mesh
                    name="cactus_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.cactus_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="cactus001"
                  position={[-1911.096, 2026.679, 1080.781]}
                  rotation={[-Math.PI / 2, 0, -1.188]}
                  scale={106.496}
                >
                  <mesh
                    name="cactus001_cactus_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.cactus001_cactus_0.geometry}
                    material={materials.cactus}
                  />
                  <mesh
                    name="cactus001_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.cactus001_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="cactus002"
                  position={[-2029.951, 1980.845, 781.751]}
                  rotation={[-2.914, -0.374, 2.52]}
                  scale={[37.17, 37.17, 57.129]}
                >
                  <mesh
                    name="cactus002_cactus_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.cactus002_cactus_0.geometry}
                    material={materials.cactus}
                  />
                  <mesh
                    name="cactus002_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.cactus002_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="bean_bag"
                  position={[-720.403, 1830.669, 1196.035]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="bean_bag_coffe_bag_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.bean_bag_coffe_bag_0.geometry}
                    material={materials.coffe_bag}
                  />
                  <mesh
                    name="bean_bag_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.bean_bag_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="tap002"
                  position={[-1792.973, 670.47, -83.052]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[131.159, 141.428, 174.835]}
                >
                  <mesh
                    name="tap002_coffe_machine_industrial_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.tap002_coffe_machine_industrial_0.geometry}
                    material={materials.coffe_machine_industrial}
                  />
                  <mesh
                    name="tap002_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.tap002_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="teapot"
                  position={[-1922.549, 1812.881, 37.288]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={124.829}
                >
                  <mesh
                    name="teapot_teapot_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.teapot_teapot_0.geometry}
                    material={materials.teapot}
                  />
                  <mesh
                    name="teapot_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.teapot_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="teapot_bottom"
                  position={[-1919.122, 1564.272, 61.148]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={124.829}
                >
                  <mesh
                    name="teapot_bottom_teapot_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.teapot_bottom_teapot_0.geometry}
                    material={materials.teapot}
                  />
                  <mesh
                    name="teapot_bottom_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.teapot_bottom_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Viewer"
                  position={[-85.002, -20.491, -166.197]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[134.118, 121.392, 156.235]}
                >
                  <mesh
                    name="Viewer_cabinet_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Viewer_cabinet_0.geometry}
                    material={materials.cabinet}
                  />
                  <mesh
                    name="Viewer_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Viewer_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="bean_bag001"
                  position={[-299.162, 1830.609, 1196.035]}
                  rotation={[-1.672, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="bean_bag001_coffe_bag_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.bean_bag001_coffe_bag_0.geometry}
                    material={materials.coffe_bag}
                  />
                  <mesh
                    name="bean_bag001_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.bean_bag001_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Cup_small001"
                  position={[-682.092, 430.391, -560.244]}
                  rotation={[-1.573, 0.009, 0.285]}
                  scale={100}
                >
                  <mesh
                    name="Cup_small001_Cups_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cup_small001_Cups_0.geometry}
                    material={materials.Cups}
                  />
                  <mesh
                    name="Cup_small001_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cup_small001_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Cup_medium001"
                  position={[-940.985, 411.796, -951.316]}
                  rotation={[-1.585, 0.011, 0.276]}
                  scale={86.903}
                >
                  <mesh
                    name="Cup_medium001_Cups_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cup_medium001_Cups_0.geometry}
                    material={materials.Cups}
                  />
                  <mesh
                    name="Cup_medium001_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cup_medium001_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="smoke"
                  position={[-680.727, 479.813, -571.179]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="smoke_smoke_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.smoke_smoke_0.geometry}
                    material={materials.smoke}
                  />
                </group>
                <group
                  name="smoke001"
                  position={[-945.83, 408.607, -945.526]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="smoke001_smoke_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.smoke001_smoke_0.geometry}
                    material={materials.smoke}
                  />
                </group>
                <group
                  name="Chair"
                  position={[-738.406, 133.338, -1346.317]}
                  rotation={[-1.615, 0.102, 0.097]}
                  scale={[100.064, 100.053, 120.533]}
                >
                  <mesh
                    name="Chair_Chair_red_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Chair_Chair_red_0.geometry}
                    material={materials.Chair_red}
                  />
                  <mesh
                    name="Chair_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Chair_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="saucer"
                  position={[-945.227, 309.99, -943.833]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[104.701, 104.701, 13.434]}
                >
                  <mesh
                    name="saucer_plate_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.saucer_plate_0.geometry}
                    material={materials.plate}
                  />
                  <mesh
                    name="saucer_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.saucer_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="saucer001"
                  position={[-685.516, 371.456, -555.945]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[104.701, 104.701, 13.434]}
                >
                  <mesh
                    name="saucer001_plate_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.saucer001_plate_0.geometry}
                    material={materials.plate}
                  />
                  <mesh
                    name="saucer001_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.saucer001_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="coffee_liquid"
                  position={[-683.203, 468.17, -559.679]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="coffee_liquid_Cups_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.coffee_liquid_Cups_0.geometry}
                    material={materials.Cups}
                  />
                </group>
                <group
                  name="coffee_liquid2"
                  position={[-940.076, 452.973, -953.952]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={81.33}
                >
                  <mesh
                    name="coffee_liquid2_Cups_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.coffee_liquid2_Cups_0.geometry}
                    material={materials.Cups}
                  />
                </group>
                <group
                  name="Chair001"
                  position={[-1583.112, 136.645, -1461.419]}
                  rotation={[-1.602, 0.106, -0.019]}
                  scale={[100.064, 100.053, 120.533]}
                >
                  <mesh
                    name="Chair001_Chair_yellow_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Chair001_Chair_yellow_0.geometry}
                    material={materials.Chair_yellow}
                  />
                  <mesh
                    name="Chair001_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Chair001_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Chair002"
                  position={[-155.724, 133.338, -1438.75]}
                  rotation={[-1.651, 0.076, 0.504]}
                  scale={[100.064, 100.053, 120.533]}
                >
                  <mesh
                    name="Chair002_Chair_pink_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Chair002_Chair_pink_0.geometry}
                    material={materials.Chair_pink}
                  />
                  <mesh
                    name="Chair002_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Chair002_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="saucer002"
                  position={[-505.716, 316.448, -955.782]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[140.431, 140.431, 18.018]}
                >
                  <mesh
                    name="saucer002_plate_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.saucer002_plate_0.geometry}
                    material={materials.plate}
                  />
                  <mesh
                    name="saucer002_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.saucer002_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Cake_orange"
                  position={[153.425, 256.199, -16.253]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={59.156}
                >
                  <mesh
                    name="Cake_orange_Cake_orange_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cake_orange_Cake_orange_0.geometry}
                    material={materials.Cake_orange}
                  />
                  <mesh
                    name="Cake_orange_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cake_orange_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Cake_orange001"
                  position={[-503.381, 459.222, -980.459]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={71.346}
                >
                  <mesh
                    name="Cake_orange001_Cake_orange_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cake_orange001_Cake_orange_0.geometry}
                    material={materials.Cake_orange}
                  />
                  <mesh
                    name="Cake_orange001_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cake_orange001_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Cake_orange002"
                  position={[-419.164, 342.884, -975.228]}
                  rotation={[3.08, -0.284, 2.351]}
                  scale={71.346}
                >
                  <mesh
                    name="Cake_orange002_Cake_orange_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cake_orange002_Cake_orange_0.geometry}
                    material={materials.Cake_orange}
                  />
                  <mesh
                    name="Cake_orange002_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cake_orange002_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Cake_strawberry"
                  position={[36.786, 529.583, 202.527]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={64.572}
                >
                  <mesh
                    name="Cake_strawberry_Cake_strawberry_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cake_strawberry_Cake_strawberry_0.geometry}
                    material={materials.Cake_strawberry}
                  />
                  <mesh
                    name="Cake_strawberry_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cake_strawberry_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Cupcake"
                  position={[26.697, 511.233, -5.933]}
                  rotation={[-Math.PI / 2, -0.084, 0]}
                  scale={57.009}
                >
                  <mesh
                    name="Cupcake_Cupcake_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cupcake_Cupcake_0.geometry}
                    material={materials.Cupcake}
                  />
                  <mesh
                    name="Cupcake_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Cupcake_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Display"
                  position={[-311.254, 2605.482, 1230.351]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[100, 109.821, 100]}
                >
                  <mesh
                    name="Display_Walls_addons_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Display_Walls_addons_0.geometry}
                    material={materials.Walls_addons}
                  />
                  <mesh
                    name="Display_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Display_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Display001"
                  position={[-1501.081, 2605.482, 1230.351]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[100, 109.821, 100]}
                >
                  <mesh
                    name="Display001_Walls_addons_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Display001_Walls_addons_0.geometry}
                    material={materials.Walls_addons}
                  />
                  <mesh
                    name="Display001_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Display001_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Floor"
                  position={[-793.877, -147.424, -8.871]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Floor_Walls_floor_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Floor_Walls_floor_0.geometry}
                    material={materials.Walls_floor}
                  />
                  <mesh
                    name="Floor_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Floor_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Painting"
                  position={[-2152.278, 2490.112, -204.172]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Painting_Walls_addons_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Painting_Walls_addons_0.geometry}
                    material={materials.Walls_addons}
                  />
                  <mesh
                    name="Painting_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Painting_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Souffle"
                  position={[138.008, 262.848, 193.202]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={71.056}
                >
                  <mesh
                    name="Souffle_Souffle_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Souffle_Souffle_0.geometry}
                    material={materials.Souffle}
                  />
                  <mesh
                    name="Souffle_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Souffle_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
                <group
                  name="Walls"
                  position={[-1365.568, 1571.701, 632.723]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Walls_Walls_floor_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Walls_Walls_floor_0.geometry}
                    material={materials.Walls_floor}
                  />
                  <mesh
                    name="Walls_Outline_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Walls_Outline_0.geometry}
                    material={materials.Outline}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/anime_cute_cafe.glb");
